jenkins:
  systemMessage: "{{ cluster_name }} Jenkins — managed by Ansible JCasC"
  labelString: "master linux default"
  numExecutors: "{{ jenkins_num_executors }}"
  mode: EXCLUSIVE
  disableRememberMe: false
  markupFormatter: "plainText"
  myViewsTabBar: "standard"
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 1
  slaveAgentPort: -1
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"

  globalNodeProperties:
    - envVars:
        env:
          - key: "DOCKER_REGISTRY"
            value: "{{ docker_registry }}"
          - key: "OPS_GIT_REPO"
            value: "{{ git_repo_ssh }}"
          - key: "ARGOCD_SERVER"
            value: "{{ argocd_url }}"
          - key: "GIT_CREDS_ID"
            value: "{{ jenkins_git_creds_id }}"
          - key: "DOCKER_CREDS_ID"
            value: "{{ jenkins_docker_creds_id }}"
          - key: "JENKINS_GIT_USER_CREDS_ID"
            value: "{{ jenkins_git_user_creds_id }}"
          - key: "ARGOCD_CREDS_ID"
            value: "{{ jenkins_argocd_creds_id }}"
          - key: "JENKINS_AGENT_LABEL"
            value: "{{ jenkins_agent_label }}"
          - key: "GIT_COMMIT_USER"
            value: "{{ jenkins_git_commit_user }}"
          - key: "GIT_COMMIT_EMAIL"
            value: "{{ jenkins_git_commit_email }}"

  authorizationStrategy:
    projectMatrix:
      entries:
        - group:
            name: authenticated
            permissions:
              - Credentials/View
              - Job/Build
              - Job/Cancel
              - Job/Discover
              - Job/Read
              - Job/Workspace
              - Overall/Read
              - Run/Replay
              - View/Read
        - user:
            name: anonymous
            permissions:
              - Overall/Read
        - user:
            name: "{{ jenkins_admin_username }}"
            permissions:
              - Agent/Build
              - Agent/Configure
              - Agent/Connect
              - Agent/Create
              - Agent/Delete
              - Agent/Disconnect
              - Credentials/Create
              - Credentials/Delete
              - Credentials/ManageDomains
              - Credentials/Update
              - Credentials/View
              - Job/Build
              - Job/Cancel
              - Job/Configure
              - Job/Create
              - Job/Delete
              - Job/Discover
              - Job/Move
              - Job/Read
              - Job/Workspace
              - Overall/Administer
              - Overall/Read
              - Run/Delete
              - Run/Replay
              - Run/Update
              - View/Configure
              - View/Create
              - View/Delete
              - View/Read
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "{{ jenkins_admin_username }}"
          name: "Jenkins Administrator"
          password: "{{ jenkins_admin_password }}"

unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  scmGit:
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "{{ jenkins_git_commit_email }}"
    url: "http://{{ ansible_host }}:{{ jenkins_port }}/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"

tool:
  git:
    installations:
      - home: "git"
        name: "Default"

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "noHostKeyVerificationStrategy"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "{{ jenkins_git_user_creds_id }}"
              username: "{{ jenkins_git_username }}"
              password: "{{ jenkins_git_password }}"
              description: "Jenkins Git User"
              scope: GLOBAL
          - usernamePassword:
              id: "{{ jenkins_docker_creds_id }}"
              username: "{{ docker_registry_username }}"
              password: "{{ docker_registry_password }}"
              description: "Docker registry credentials"
              scope: GLOBAL
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "{{ jenkins_git_creds_id }}"
              description: "Git SSH credentials"
              username: "jenkins"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:/var/lib/jenkins/creds/ssh_privkey}"
          - usernamePassword:
              id: "{{ jenkins_argocd_creds_id }}"
              username: "{{ argocd_admin_user }}"
              password: "{{ argocd_password }}"
              description: "ArgoCD credentials"
              scope: GLOBAL
