apiVersion: v1
appVersion: 0.1.0
name: helm-common
description: Reusable Helm library chart shared by all application charts
version: 0.1.1
maintainers:
  - name: Sritharan K
    url: https://www.skengineer.be
