---
- name: Determine kubectl download URL
  set_fact:
    kubectl_url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"

- name: Download kubectl
  get_url:
    url: "{{ kubectl_url }}"
    dest: /usr/local/bin/kubectl
    mode: "0755"
  when: ansible_os_family in ['Debian', 'RedHat', 'Fedora']

- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_version_output

- name: Display kubectl version
  debug:
    msg: "kubectl version installed: {{ kubectl_version_output.stdout }}"
