- name: Install Java (RHEL/CentOS/Rocky)
  yum:
    name:
      - java-{{ java_version }}-openjdk
      - java-{{ java_version }}-openjdk-devel
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Java (Debian/Ubuntu)
  apt:
    name:
      - openjdk-{{ java_version }}-jdk
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
