---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgADdPXwBxmehXmrNE94ov/4EiSIgQj/zGZ8T8qvlX3AuKu7A43tHqpVXRSFKc6BVrxsIDiUfdCdq+ilmp39AboN9o+iHCUcXH8FuGg1vTcXE7SDRFTz+dqdw5vNgzjjZzW+f1zUMP2w3M+nXijg1u8e/dEIAcgLzkGNEpOvNtSI4pC5U9euKKaMYmIOzey2xwcwEK4AwLnUWq03XI6fqrvTKEMD3WbBBOVPgvugiSRPK5zBDcgF3R1bjecizH6PeARqbG0yCVGe3ckUwNHOxVmQkruhJYh09maAsK/Jg9QnE/G7mKMWo1J+jrDMl/eBuGc/0+TPGONZSxakmnkqtnWkYQlA54iplp/WH9OvRKRztv3rpEf40RkXf4eTdFaLfebwkrj4Yc3bfHVLjwx+VJHYf486Wbpzgkw/Vxwn5YtrpYtwD4F1/6TBCt1EuctRQJSPI6n1otq1PgtvMxxrUG1Y9v6cWqX1BE9CMFDfJwFYKp7uLciiu8DqehFyFDPaUJ4hfpYO1uUROnKDaIZWYWdQCvhH+v+MHqNtUvxf7bwZMBFHNWOyZbh9tjWLhCp4IxNX72+OoMz4bDEJ70Zsl9dnyIl8D+EYhugsnVPWJ7JRwgKpAmnjdc9ATcX4MLV50bGkhOux+TeY5p4Wz+SDagSxYgVd4LfwQUgIjaOPSS4PYS7U3CthWCoYTKEsFCLwjToYlMctZnABrC8tSfu3sXCvV/jg3jeL5Ra/sVVSeCxgS40oNV1IYYrHYT15wS9R7h8zBux5whlkum7y1sE47W1v0rrKft+lPDAoOkRBBi2EVpoFofCjACwnUBPG4nKMBbxHLN8E+2VQzjIEWplKYVZI8/JpscVKcfO/z25+U3mpq8DLTQxa9ZXYOdbeXj/9ZcmG6hhkr49ox7qmeJGTMa7nuWpbodPBtLit
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: prod
    type: kubernetes.io/dockerconfigjson
