apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-readiness-probe
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: require-readiness-probe
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                {{- range .Values.enforcedNamespaces }}
                - {{ . }}
                {{- end }}
      validate:
        message: "Pods must define a readinessProbe."
        pattern:
          spec:
            containers:
              - readinessProbe: {}
