# -----------------------------------------------------------------------------
# Author : Sritharan K (https://www.skengineer.be)
# License: MIT
# -----------------------------------------------------------------------------
{{- if .Values.enabledDeployment }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" $ }}
  labels:
    tier: {{ .Values.tier }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "nginx-tplValue" ( dict "value" .Values.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ .Values.name }}
    tier: {{ .Values.tier }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.containerPort }}
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.http)) }}
    nodePort: {{ .Values.service.nodePorts.http }}
    {{- end }}

{{- if .Values.service.enabledHeadless }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" $ }}-headless
  labels:
    tier: {{ .Values.tier }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "nginx-tplValue" ( dict "value" .Values.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ .Values.name }}
    tier: {{ .Values.tier }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.containerPort }}
{{- end }}
{{- end }}
